title: "Binomial-2"
pulseSeq:
  - t: 0
    FA: 45
  - t: 2.3
    FA: 45
TR: 10
nTR: 1 
B0: 1.5
B1: 5.0 
components:
  - name: "water"
    CS: 0.0
    T1: 1.0e+9
    T2: 1.0e+9
  - name: "fat"
    CS: -3.40389262
    T1: 1.0e+9
    T2: 1.0e+9
nIsochromats: 15
isochromatStep: 0.03
speed: 0.001
outFile3D: "binomial2_3D.gif"
outFileMxy: ""
outFileMz: ""