title: Binomial-7
pulseSeq:
  - t: 0
    FA: 1.4
  - t: 2.3
    FA: 8.4
  - t: 4.6
    FA: 21.1
  - t: 6.9
    FA: 28.1
  - t: 9.2
    FA: 21.1
  - t: 11.5
    FA: 8.4
  - t: 13.8
    FA: 1.4
TR: 20
nTR: 1 
B0: 1.5 
B1: 5.0 
components:
  - name: water
    CS: 0.0
    T1: 1.0e+9
    T2: 1.0e+9
  - name: fat
    CS: -3.40389262
    T1: 1.0e+9
    T2: 1.0e+9
nIsochromats: 15
isochromatStep: 0.03
speed: 0.001
output:
  - type: 3D
    file: binomial7_3D.gif