title: Example config
pulseSeq:
    - t: 2
      FA: 45
      B1: inf
    - t: 5
      dur: 1
      B1: 3
    - t: 10
      dur: 4
      FA: 180
      Gz: 5
    - t: 15
      dur: 5
      Gx: 10
      Gy: 10
    - t: 23
      spoil: true
TR: 25
nTR: 2 
B0: 3.0 
B1: 10
components:
    - name: "tissue #1"
      CS: 0.0
      T1: 1000.0
      T2: 100.0
    - name: "tissue #2"
      CS: 3.4
      T1: 300.0
      T2: 80.0
locations:
  "tissue #1":
    [[[0,   0,   0  ], 
      [0.5, 0.5, 0  ], 
      [0.5, 0.5, 0.5]]]
  "tissue #2":
    [[[0.5, 0.5, 0.5], 
      [0,   0,   0.5], 
      [0,   0,   0  ]]]
M0:
  "tissue #1":
    [[[0,0,0], [0,0,0], [0,0,0]],
     [[0,0,.5], [0,0,.5], [0,0,0]],
     [[0,0,.5], [0,0,.5], [0,0,.5]]]
  "tissue #2":
    [[[0,0,.5], [0,0,.5], [0,0,.5]],
     [[0,0,0], [0,0,0], [0,0,.5]],
     [[0,0,0], [0,0,0], [0,0,0]]]
locSpacing: 0.001
nIsochromats: 20
isochromatStep: 0.01
speed: 0.003
output: 
  - type: 3D
    file: example_3D.gif
    drawAxes: False
    dpi: 100
  - type: xy
    abs: true
    file: example_xy_abs.gif
  - type: xy
    abs: false
    file: example_xy_RI.mp4
    dpi: 72
  - type: z
    file: example_z.gif
  - type: psd
    file: example_psd.gif