title: "Fat and Water Precession (1.5 T)"
pulseSeq:
  - t: 0
    FA: 90
TR: 15
nTR: 1 
B0: 1.5 
B1: 100 
components:
  - name: "water"
    Meq: 1.0
    CS: 0.0
    T1: 870
    T2: 47
  - name: "fat"
    Meq: 1.0
    CS: 3.4
    T1: 260
    T2: 84 
nIsochromats: 1
isochromatStep: 0.01
speed: 0.001
outFile3D: "fatwater_3D.gif"
outFileMxy: "fatwater_tra.gif"
outFileMz: ""