title: FLAIR
pulseSeq:
  - t: 0
    FA: 180
  - t: 1680
    FA: 90
  - t: 1710
    FA: 180
TR: 2700
B0: 1.5
B1: inf
components:
  - name: CSF
    CS: 0.0
    T1: 2400
    T2: 160
  - name: WM
    CS: 0.0
    T1: 790
    T2: 92
  - name: GM
    CS: 0.0
    T1: 920
    T2: 101
speed: 0.1
output:
  - type: 3D
    file: FLAIR_3D.gif
  - type: z
    file: FLAIR_Mz.gif