title: "FLAIR"
pulseSeq:
  - t: 0
    FA: 180
  - t: 1680
    FA: 90
  - t: 1710
    FA: 180
TR: 2700
nTR: 1
B0: 1.5
B1: 100
components:
  - name: "CSF"
    CS: 0.0
    T1: 2400
    T2: 160
  - name: "WM"
    CS: 0.0
    T1: 790
    T2: 92
  - name: "GM"
    CS: 0.0
    T1: 920
    T2: 101
nIsochromats: 1
isochromatStep: 0.01
speed: 0.1
outFile3D: "FLAIR_3D.gif"
outFileMxy: ""
outFileMz: "FLAIR_Mz.gif"