title: FSE
pulseSeq:
  - t: 0
    FA: 90
  - t: 10
    FA: 180
  - t: 30
    FA: 180
  - t: 50
    FA: 180
  - t: 70
    FA: 180
TR: 130
B0: 1.5
B1: inf
nIsochromats: 30
isochromatStep: 0.02
speed: 0.01
output:
  - type: 3D
    file: FSE_3D.gif