title: "space encoding"
pulseSeq:
  - t: 0
    FA: 90
    dur: 0
  - t: 0
    Gx: 1
    dur: 20
TR: 20
nTR: 1
B0: 1.5
B1: 1
components:
  - name: "something"
    CS: 3.0
    T1: 200.
    T2: 80.
locations:
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
nIsochromats: 1
isochromatStep: 0.01
speed: 0.005
output:
  - type: 3D
    file: space_3D.gif
  - type: xy
    abs: false
    file: space_xy.gif
  - type: psd
    file: space_psd.gif