title: Spatial Excitation
pulseSeq:
  - t: 0
    FA: 90
    dur: 2
    Gx: 30
TR: 10
B0: 1.5
locations:
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
speed: 0.005
output:
  - type: 3D
    file: SpExc_3D.gif
  - type: psd
    file: SpExc_psd.gif