title: "Spoiled Gradient Echo"
pulseSeq:
  - t: 0
    FA: 15
  - t: 5
    FA: 0
TR: 5
nTR: 15
B0: 1.5
B1: 1.0
components:
  - name: ""
    Meq: 1.0
    CS: 0.0
    T1: 60.0
    T2: 55.0
nIsochromats: 1
isochromatStep: 0.01
speed: 0.005
outFile3D: "SPGR_3D.gif"
outFileMxy: ""
outFileMz: ""